export const USER_FUND_ACCOUNT_REQUEST = 'USER_FUND_ACCOUNT_REQUEST';
export const USER_FUND_ACCOUNT_SUCCESS = 'USER_FUND_ACCOUNT_SUCCESS';
export const USER_FUND_ACCOUNT_FAIL = 'USER_FUND_ACCOUNT_FAIL';

export const USER_ACCOUNT_FUND_BALANCE_REQUEST = 'USER_ACCOUNT_FUND_BALANCE_REQUEST';
export const USER_ACCOUNT_FUND_BALANCE_SUCCESS = 'USER_ACCOUNT_FUND_BALANCE_SUCCESS';
export const USER_ACCOUNT_FUND_BALANCE_FAIL = 'USER_ACCOUNT_FUND_BALANCE_FAIL';

export const USER_ACCOUNT_FUND_LIST_REQUEST = 'USER_ACCOUNT_FUND_LIST_REQUEST';
export const USER_ACCOUNT_FUND_LIST_SUCCESS = 'USER_ACCOUNT_FUND_LIST_SUCCESS';
export const USER_ACCOUNT_FUND_LIST_FAIL = 'USER_ACCOUNT_FUND_LIST_FAIL';

export const SET_MAX_FUND_WITHDRAWAL_REQUEST = 'SET_MAX_FUND_WITHDRAWAL_REQUEST';
export const SET_MAX_FUND_WITHDRAWAL_SUCCESS = 'SET_MAX_FUND_WITHDRAWAL_SUCCESS';
export const SET_MAX_FUND_WITHDRAWAL_FAIL = 'SET_MAX_FUND_WITHDRAWAL_FAIL';

export const TOGGLE_ACCCOUNT_FUND_REQUEST = 'TOGGLE_ACCCOUNT_FUND_REQUEST';
export const TOGGLE_ACCCOUNT_FUND_SUCCESS = 'TOGGLE_ACCCOUNT_FUND_SUCCESS';
export const TOGGLE_ACCCOUNT_FUND_FAIL = 'TOGGLE_ACCCOUNT_FUND_FAIL';
