export const USER_FUND_ACCOUNT_REQUEST = 'USER_FUND_ACCOUNT_REQUEST';
export const USER_FUND_ACCOUNT_SUCCESS = 'USER_FUND_ACCOUNT_SUCCESS';
export const USER_FUND_ACCOUNT_FAIL = 'USER_FUND_ACCOUNT_FAIL';

export const USER_ACCOUNT_FUND_BALANCE_REQUEST = 'USER_ACCOUNT_FUND_BALANCE_REQUEST';
export const USER_ACCOUNT_FUND_BALANCE_SUCCESS = 'USER_ACCOUNT_FUND_BALANCE_SUCCESS';
export const USER_ACCOUNT_FUND_BALANCE_FAIL = 'USER_ACCOUNT_FUND_BALANCE_FAIL';

export const USER_ACCOUNT_FUND_LIST_REQUEST = 'USER_ACCOUNT_FUND_LIST_REQUEST';
export const USER_ACCOUNT_FUND_LIST_SUCCESS = 'USER_ACCOUNT_FUND_LIST_SUCCESS';
export const USER_ACCOUNT_FUND_LIST_FAIL = 'USER_ACCOUNT_FUND_LIST_FAIL';
