export const PAYMENT_CREATE_REQUEST = 'PAYMENT_CREATE_REQUEST';
export const PAYMENT_CREATE_SUCCESS = 'PAYMENT_CREATE_SUCCESS';
export const PAYMENT_CREATE_FAIL = 'PAYMENT_CREATE_FAIL';

export const PAYMENT_LIST_REQUEST = 'PAYMENT_LIST_REQUEST';
export const PAYMENT_LIST_SUCCESS = 'PAYMENT_LIST_SUCCESS';
export const PAYMENT_LIST_FAIL = 'PAYMENT_LIST_FAIL';
 
export const ADMIN_PAYMENT_LIST_REQUEST = 'ADMIN_PAYMENT_LIST_REQUEST';
export const ADMIN_PAYMENT_LIST_SUCCESS = 'ADMIN_PAYMENT_LIST_SUCCESS';
export const ADMIN_PAYMENT_LIST_FAIL = 'ADMIN_PAYMENT_LIST_FAIL';

export const LIST_ALL_PAYMENTS_REQUEST = 'LIST_ALL_PAYMENTS_REQUEST';
export const LIST_ALL_PAYMENTS_SUCCESS = 'LIST_ALL_PAYMENTS_SUCCESS';
export const LIST_ALL_PAYMENTS_FAIL = 'LIST_ALL_PAYMENTS_FAIL';

export const GET_PAYMENT_API_KEYS_REQUEST = 'GET_PAYMENT_API_KEYS_REQUEST';
export const GET_PAYMENT_API_KEYS_SUCCESS = 'GET_PAYMENT_API_KEYS_SUCCESS';
export const GET_PAYMENT_API_KEYS_FAIL = 'GET_PAYMENT_API_KEYS_FAIL';

export const CREATE_PAYMENT_LINK_REQUEST = 'CREATE_PAYMENT_LINK_REQUEST';
export const CREATE_PAYMENT_LINK_SUCCESS = 'CREATE_PAYMENT_LINK_SUCCESS';
export const CREATE_PAYMENT_LINK_FAIL = 'CREATE_PAYMENT_LINK_FAIL';

export const UPDATE_PAYMENT_LINK_REQUEST = 'UPDATE_PAYMENT_LINK_REQUEST';
export const UPDATE_PAYMENT_LINK_SUCCESS = 'UPDATE_PAYMENT_LINK_SUCCESS';
export const UPDATE_PAYMENT_LINK_FAIL = 'UPDATE_PAYMENT_LINK_FAIL';

export const GET_PAYMENT_LINK_DETAIL_REQUEST = 'GET_PAYMENT_LINK_DETAIL_REQUEST';
export const GET_PAYMENT_LINK_DETAIL_SUCCESS = 'GET_PAYMENT_LINK_DETAIL_SUCCESS';
export const GET_PAYMENT_LINK_DETAIL_FAIL = 'GET_PAYMENT_LINK_DETAIL_FAIL';

export const GET_SELLER_PAYMENT_LINKS_REQUEST = 'GET_SELLER_PAYMENT_LINKS_REQUEST';
export const GET_SELLER_PAYMENT_LINKS_SUCCESS = 'GET_SELLER_PAYMENT_LINKS_SUCCESS';
export const GET_SELLER_PAYMENT_LINKS_FAIL = 'GET_SELLER_PAYMENT_LINKS_FAIL';

export const DELETE_PAYMENT_LINK_REQUEST = 'DELETE_PAYMENT_LINK_REQUEST';
export const DELETE_PAYMENT_LINK_SUCCESS = 'DELETE_PAYMENT_LINKS_SUCCESS';
export const DELETE_PAYMENT_LINK_FAIL = 'DELETE_PAYMENT_LINKS_FAIL';
