// PromiseConstants.js 
export const GET_BUYER_PROMISE_REQUEST = 'GET_BUYER_PROMISE_REQUEST';
export const GET_BUYER_PROMISE_SUCCESS = 'GET_BUYER_PROMISE_SUCCESS';
export const GET_BUYER_PROMISE_FAIL = 'GET_BUYER_PROMISE_FAIL';

export const GET_SELLER_PROMISE_REQUEST = 'GET_SELLER_PROMISE_REQUEST';
export const GET_SELLER_PROMISE_SUCCESS = 'GET_SELLER_PROMISE_SUCCESS';
export const GET_SELLER_PROMISE_FAIL = 'GET_SELLER_PROMISE_FAIL';

export const BUYER_CONFIRM_PROMISE_REQUEST = 'BUYER_CONFIRM_PROMISE_REQUEST';
export const BUYER_CONFIRM_PROMISE_SUCCESS = 'BUYER_CONFIRM_PROMISE_SUCCESS';
export const BUYER_CONFIRM_PROMISE_FAIL = 'BUYER_CONFIRM_PROMISE_FAIL';

export const SELLER_CONFIRM_PROMISE_REQUEST = 'SELLER_CONFIRM_PROMISE_REQUEST';
export const SELLER_CONFIRM_PROMISE_SUCCESS = 'SELLER_CONFIRM_PROMISE_SUCCESS';
export const SELLER_CONFIRM_PROMISE_FAIL = 'SELLER_CONFIRM_PROMISE_FAIL';
