// transactionConstants.js
export const USER_TRANSACTION_REQUEST = 'USER_TRANSACTION_REQUEST';
export const USER_TRANSACTION_SUCCESS = 'USER_TRANSACTION_SUCCESS';
export const USER_TRANSACTION_FAIL = 'USER_TRANSACTION_FAIL';
